### ISSUE TITLE
Code Relasing date

### ISSUE THREAD

**Issue by ShoufaChen** [Xiaodongsuper/M5Product_dataset#1]
Hi,

Thanks for your awesome work!

I noticed that the Data Toolkits will be open very soon in the webpage.

I was wondering would you mind sharing a more specific date?  In a week or a month?

Thanks in advance.

**Comment by Xiaodongsuper** [comment]
Thank you for your attention. Sorry for reply late.  Now, we have released several codes in this link https://github.com/Xiaodongsuper/M5Product_toolkit. We are preparing the OCR modalities and English versions for our dataset. For other codes including models, we will release them asap.
